### ISSUE TITLE
Quick UI enhancements

### ISSUE THREAD

**Issue by JLRaisaro** [CHUV-DS/glowing-bear-medco-bioref#28]
- [x] rename statistics results tab => Use “Reference Interval Estimation” instead of “Statistics Results'' as tab title.
- [x] use "reference interval" instead of reference values/ranges everywhere in the UI
- [x] change colors on the histogram => Dark blue for the central part (HEX: #188dd2); Dark blue for the reference interval (vertical non-dashed lines, HEX: #188dd2); Light blue for the range of the confidence intervals (HEX: #a6e1fa); Light blue for the confidence interval borders (vertical dashed lines, HEX: #a6e1fa); Light gray (including light pattern, e.g. dots or diagonal lines) for the excluded parts outside the confidence intervals (HEX: #eaebec).
- [x] Change labels appearance of histogram (The Label “Frequency” is too close to the y-axis (as
compared to the “Value [test value]” to the x-axis). For the Swiss BioRef dataset, the
x-axis should be labeled as “analyte name [ unit of measurement ]
- [x] Rephrase head of the result field: Currently: “The reference interval (95%) is:” => New: “The 95% reference interval (90% confidence) is:
- [x] Change the order of analyses and cohort definition in the query summary (same order as in the cohort building panel)
- [x] Add a box around or a line to clearly separate the Analytes dropping zone from the cohort building dropping zone
- [x] Hide subjects count information
- [x] Add a tooltip explaining what the treat group independently option entails
- [x] Add copyrights notice in html page
- [x] Add copyrights notice in pdf export

**Comment by Harald-W** [comment]
> @Harald-W : please provide copyright notice that you would like to have in the UI

**_Copyright notices to be displayed both in the user interface_ AND _on the PDF-report:_**

**LOINC:**
**"This material contains content from LOINC (http://loinc.org/). LOINC is copyright © 1995-2022, Regenstrief Institute, Inc. and the Logical Observation Identifiers Names and Codes (LOINC) Committee and is available at no cost under the license at http://loinc.org/license. LOINC® is a registered United States trademark of Regenstrief Institute, Inc."**

**GMDN:**
_GMDN copyright statement received from GMDN Agency:
"Wherever the Licensee publishes or displays any GMDN Codes, Term Names, Definitions, Collective Terms, the Licensee shall display **with reasonable prominence** a proprietary notice in accordance with the following wording:
GMDN ® is a registered trademark of The GMDN Agency. All rights reserved. The copyright and database rights in the original GMDN materials are owned by The GMDN Agency Ltd 2005-2022. Used under licence from The GMDN Agency Ltd.
[...]
The statement should be reviewed annually, and the date updated to the current year."_
I therefore suggest the full-length version:
**"GMDN ® is a registered trademark of The [GMDN Agency](https://www.gmdnagency.org/). All rights reserved. The copyright and database rights in the original GMDN materials are owned by The GMDN Agency Ltd 2005-2022. Used under licence from The GMDN Agency Ltd."**

**GUDID:**
**"Global Unique Device Identification codes from the Global Unique Device Identification Database (GUDID) have been retrieved at the [AccessGUDID-portal](https://accessgudid.nlm.nih.gov/) and are a courtesy of the the [U.S. National Library of Medicine](https://www.nlm.nih.gov/) in collaboration with the [U.S. Food and Drug Administration](https://www.fda.gov/)."**

**Comment by JLRaisaro** [comment]
It is a lot of text. Where do you suggest to display it in the UI?

**Comment by Harald-W** [comment]
We can use **short copyright notices at the bottom of the UI** (Try out different font sizes - notices need to be **clearly legible!**):
**LOINC** ® codes and long common names: © 1995-2022, [Regenstrief Institute, Inc.](https://www.regenstrief.org/) and the [LOINC](http://loinc.org/) Committee
**GMDN** ® codes, terms, and descriptions: © [GMDN Agency](https://www.gmdnagency.org/) 2005-2022.
**GUDI** codes: courtesy of the the [U.S. National Library of Medicine](https://www.nlm.nih.gov/) in collaboration with the [U.S. Food and Drug Administration](https://www.fda.gov/)
**ICD-10-GM** codes and descriptions: © 2022 [Bundesinstitut für Arzneimittel und Medizinprodukte](https://www.bfarm.de/EN/Code-systems/Classifications/ICD/ICD-10-GM/_node.html)
 
**Extended copyright notices should be used at the bottom of the page of PDF-report:**
**LOINC:** This material contains content from LOINC (http://loinc.org/). LOINC is copyright © 1995-2022, Regenstrief Institute, Inc. and the Logical Observation Identifiers Names and Codes (LOINC) Committee and is available at no cost under the license at http://loinc.org/license. LOINC® is a registered United States trademark of Regenstrief Institute, Inc.
**GMDN:** GMDN ® is a registered trademark of The GMDN Agency. All rights reserved. The copyright and database rights in the original GMDN materials are owned by The GMDN Agency Ltd 2005-2022. Used under licence from The GMDN Agency Ltd.
**GUDI:** Global Unique Device Identification codes from the Global Unique Device Identification Database (GUDID) have been retrieved at the [AccessGUDID-portal](https://accessgudid.nlm.nih.gov/) and are a courtesy of the the [U.S. National Library of Medicine](https://www.nlm.nih.gov/) in collaboration with the [U.S. Food and Drug Administration](https://www.fda.gov/).
**ICD-10-GM:** © 2022 German Federal Institute for Drugs and Medical Devices (Bundesinstitut für Arzneimittel und Medizinprodukte [BfArM](https://www.bfarm.de/EN/Home/_node.html)) on behalf of the German Federal Ministry of Health (Bundesministerium für Gesundheit [BMG](https://www.bundesgesundheitsministerium.de/)) with the participation of the ICD Working Group of the Board of Trustees for Questions of Classification in Health Care ([KKG](https://www.bfarm.de/DE/Kodiersysteme/Kooperationen-und-Projekte/KKG/_node.html))

**Comment by JLRaisaro** [comment]
Ok, Simon can try to do this. Thanks!

**Comment by Harald-W** [comment]
Let's aim for a pop up-window (like the info-field next to "Run"-button", but featuring bigger font size when shown).
It should become visible when one mouses over a field "Copyright notices" located in the bottom bar of the UI.
We will see whether this can fit short or long version.
Leading abbreviation (LOINC, GMDN, GUDI, ICD-10-GM) should be highlighted (bold).

**Comment by SimonCommits** [comment]
https://github.com/CHUV-DS/glowing-bear-medco-bioref/commit/3e01cb46039864f968ca1cc418ec534159b3844b

**Comment by Harald-W** [comment]
- There should be hyperlinks to all providers, either the provider name featuring a hyperlink, or the URL in brackets after the provider name.
- SNOMED CT and UCUM should be included to be on the safe side.
- The button in the user interface to display the Copyright notice should be labelled with "Copyright notice" (capital "C") rather than "copyright notice"
- The terminologies are sorted alphabetically in the new suggestion below.
- The space between each provider in the pop up-window is very suitable.

**Use extended copyright notices in the pop up-window in the user interface:**
**GMDN:** GMDN® is a registered trademark of The [GMDN Agency](https://www.gmdnagency.org/). All rights reserved. The copyright and database rights in the original GMDN materials are owned by The GMDN Agency Ltd 2005-2022. Used under licence from The GMDN Agency Ltd.
**GUDI:** Global Unique Device Identification codes from the Global Unique Device Identification Database (GUDID) have been retrieved at the [AccessGUDID-portal](https://accessgudid.nlm.nih.gov/) and are a courtesy of the the [U.S. National Library of Medicine](https://www.nlm.nih.gov/) in collaboration with the [U.S. Food and Drug Administration](https://www.fda.gov/).
**ICD-10-GM:** © 2022 German Federal Institute for Drugs and Medical Devices (Bundesinstitut für Arzneimittel und Medizinprodukte [BfArM](https://www.bfarm.de/EN/Home/_node.html)) on behalf of the German Federal Ministry of Health (Bundesministerium für Gesundheit [BMG](https://www.bundesgesundheitsministerium.de/)) with the participation of the ICD Working Group of the Board of Trustees for Questions of Classification in Health Care ([KKG](https://www.bfarm.de/DE/Kodiersysteme/Kooperationen-und-Projekte/KKG/_node.html))
**LOINC:** LOINC is copyright © 1995-2022, [Regenstrief Institute, Inc.](https://www.regenstrief.org/) and the Logical Observation Identifiers Names and Codes ([LOINC](http://loinc.org/)) Committee and is available at no cost under the license at http://loinc.org/license. LOINC® is a registered United States trademark of [Regenstrief Institute, Inc.](https://www.regenstrief.org/).
**SNOMED CT:** SNOMED CT is copyright © SNOMED International 2021 v3.15.1., [SNOMED CT international](http://www.snomed.org/). See [license details](https://mlds.ihtsdotools.org/#/landing/CH?lang=en).
**UCUM:** The Unified Code for Units of Measure ([UCUM](https://ucum.nlm.nih.gov/)), also known as the “UCUM Specification,” is copyright ©1999-2021, [Regenstrief Institute, Inc.](https://www.regenstrief.org/), Inc. and The UCUM Organization, Indianapolis, IN. All rights reserved. See [license details](https://ucum.org/trac/wiki/license).


Use **short copyright notices at the bottom of the page of PDF-report**:
**GMDN** ® codes, terms, and descriptions: © [GMDN Agency](https://www.gmdnagency.org/) 2005-2022.
**GUDI** codes: courtesy of the the [U.S. National Library of Medicine](https://www.nlm.nih.gov/) in collaboration with the [U.S. Food and Drug Administration](https://www.fda.gov/)
**ICD-10-GM** codes and descriptions: © 2022 [Bundesinstitut für Arzneimittel und Medizinprodukte](https://www.bfarm.de/EN/Code-systems/Classifications/ICD/ICD-10-GM/_node.html)
**LOINC** ® codes and long common names: © 1995-2022, [Regenstrief Institute, Inc.](https://www.regenstrief.org/) and the [LOINC](http://loinc.org/) Committee
**SNOMED CT:** SNOMED CT is copyright © SNOMED International 2021 v3.15.1., [SNOMED CT international](http://www.snomed.org/).
**UCUM:** [UCUM](https://ucum.nlm.nih.gov/) is copyright ©1999-2021, [Regenstrief Institute, Inc.](https://www.regenstrief.org/), Inc. and The UCUM Organization, Indianapolis, IN. All rights reserved.

**Comment by nfreundl** [comment]
From Harald-W:

- [x] There should be hyperlinks to all providers, either the provider name featuring a hyperlink, or the URL in brackets after the provider name.
- [x] SNOMED CT and UCUM should be included to be on the safe side.
- [x]  The button in the user interface to display the Copyright notice should be labelled with "Copyright notice" (capital "C") rather than "copyright notice"
- [x] The terminologies are sorted alphabetically in the new suggestion below.
- [x] The space between each provider in the pop up-window is very suitable.
- [x]  Use extended copyright notices in the pop up-window in the user interface:
- [x] Use short copyright notices at the bottom of the page of PDF-report

**Comment by JLRaisaro** [comment]
- copyright notice => fix hyperlinks to open a new tab
- fix typo in tool tip for default filter. Just put "Set this filter as default."
@nfreundl
